import type { SiteContent } from './types';

export const en: SiteContent = {
  meta: {
    title: 'Women Skill Development Webinar',
    description: 'Learn Skills. Build Confidence. Create Your Own Opportunities.',
  },
  announcementBar: {
    message: 'Limited Seats Available | Free Live Webinar | Registration Closing Soon',
    visible: true,
  },
  eventInfo: {
    heading: 'Event Details',
    items: [
      { label: 'Date', value: '[Webinar Date]' },
      { label: 'Time', value: '[Webinar Time]' },
      { label: 'Duration', value: '90–120 Minutes' },
      { label: 'Mode', value: 'Live Online Webinar' },
      { label: 'Language', value: 'Hindi + English' },
      { label: 'Level', value: 'Beginner Friendly' },
    ],
  },
  whyImportant: {
    heading: 'Why Is This Webinar Important?',
    paragraphs: [
      'This webinar is not about telling every woman to follow the same career path. It is about helping you understand how to identify useful skills, choose a direction, build confidence, and turn learning into practical opportunities.',
      'Whether your goal is employment, freelancing, entrepreneurship, career re-entry, or personal growth, the first step is understanding what skills can create value in the real world.',
    ],
  },
  problems: {
    heading: 'Does This Sound Like You?',
    items: [
      'You want to restart your career but do not know where to begin.',
      'You have a career gap and worry that your skills are no longer relevant.',
      'You want to work from home or build an additional source of income.',
      'You want to become more confident with technology, communication, and professional work.',
      'You feel that you have potential but need direction, practical skills, and a clear starting point.',
      'You want to learn something valuable but feel overwhelmed by the number of courses and career options available.',
    ],
    closing: 'If even one of these situations feels familiar, this webinar is for you.',
  },
  lifeTransitions: {
    heading: 'Your Life Can Change. Your Skills Can Grow With You.',
    paragraphs: [
      'Your responsibilities may change over time. You may be studying today, managing a family tomorrow, taking a career break, returning to work, or deciding that you want something of your own.',
      'Your circumstances can change, but your ability to learn can continue.',
      'Skills can give you more choices and more confidence when making those decisions.',
    ],
  },
  learn: {
    heading: 'What Will You Learn in This Webinar?',
    items: [
      { title: 'Identify Valuable Skills', description: "How to identify practical and valuable skills for today's job market." },
      { title: 'Digital Skills', description: 'How digital skills can create career and work-from-home opportunities.' },
      { title: 'Communication & Confidence', description: 'How to build professional communication and confidence.' },
      { title: 'Turn Skills Into Opportunities', description: 'How to turn a learned skill into a practical opportunity.' },
    ],
  },
  framework: {
    heading: 'How to Choose the Right Skill for Yourself',
    steps: [
      { title: 'Know Yourself', description: 'Understand your interests, strengths, experience and goals.' },
      { title: 'Understand Opportunities', description: 'Identify skills that can create value in the real world.' },
      { title: 'Choose One Direction', description: "Don't try to learn everything at once. Start with one practical direction." },
      { title: 'Learn & Practice', description: 'Learn the skill and start applying it through practical work.' },
      { title: 'Create an Opportunity', description: 'Explore how the skill can connect with jobs, freelancing, work-from-home opportunities, business or personal growth.' },
    ],
  },
  examples: {
    heading: 'See How a Skill Can Become an Opportunity',
    items: [
      { title: 'Digital Skills', chain: 'Skill → Digital Work → Career/Work Opportunity' },
      { title: 'Communication', chain: 'Skill → Better Professional Communication → Workplace Confidence' },
      { title: 'Freelancing Skill', chain: 'Skill → Portfolio/Practice → Freelancing Opportunity' },
      { title: 'Business Skill', chain: 'Skill → Practical Application → Entrepreneurship Opportunity' },
    ],
    disclaimer: 'These show a possible connection between learning and opportunity — not a guaranteed income or employment outcome.',
  },
  video: {
    heading: 'Why Is This Webinar Important for You?',
    placeholderNote: 'Intro video (60–90s) — add once recorded.',
  },
  audience: {
    heading: 'Who Is This Webinar For?',
    items: [
      { title: 'College Students', description: 'Students who want to start building useful skills early.' },
      { title: 'Homemakers', description: 'Women who want to explore learning, work or independent opportunities.' },
      { title: 'Career Restarters', description: 'Women who want to return to professional life after a career break.' },
      { title: 'Job Seekers', description: 'Women looking to improve their skills and prepare for opportunities.' },
      { title: 'Work-from-Home Seekers', description: 'Women exploring work-from-home possibilities.' },
      { title: 'Beginners', description: "Women who want to start learning but don't know where to begin." },
    ],
    cta: 'Yes, This Webinar Is For Me',
  },
  transformation: {
    heading: 'From Confusion to Clarity',
    beforeLabel: 'Before',
    afterLabel: 'After',
    before: [
      "Don't know which skill to learn",
      'Confused about career options',
      'Lack confidence',
      'Worried about career gaps',
      'Unsure how to start',
      'Overwhelmed by too many courses',
      "Don't know how to turn learning into an opportunity",
    ],
    after: [
      'Better understanding of useful skills',
      'Clearer direction',
      'Greater confidence',
      'Practical learning approach',
      'Understanding of possible opportunities',
      'A realistic learning path',
      'A clear next step',
    ],
  },
  trainer: {
    heading: 'Meet Your Trainer',
    placeholderNote: 'Trainer name, designation, company, experience, and social links go here — only real, verified information. Do not publish this section with placeholder credentials.',
  },
  testimonials: {
    heading: 'What Participants Say',
    emptyState: 'Testimonials from real participants will appear here after the first cohort. We do not publish fabricated reviews.',
  },
  bonuses: {
    heading: 'Register Today & Get These Resources',
    items: [
      'Women Skill Development Checklist',
      'Skill Selection Worksheet',
      'Career Direction Worksheet',
      'Digital Skills Starter Guide',
      'Learning Roadmap',
    ],
    note: 'Webinar recording and certificate are listed only if actually provided for this session.',
  },
  whatsappCommunity: {
    heading: 'Join Our WhatsApp Community',
    supporting:
      'Get webinar updates, reminders, and connect with other participants — free to join, open to everyone.',
    cta: 'Join WhatsApp Community',
  },
  registration: {
    heading: 'Ready to Take the First Step?',
    supporting:
      'Join this free webinar and discover practical ideas you can apply to your career, work, communication, confidence and personal growth.',
    labels: {
      fullName: 'Full Name',
      mobile: 'Mobile Number',
      whatsapp: 'WhatsApp Number',
      email: 'Email Address',
      city: 'City',
      profession: 'Profession',
      goal: 'Why do you want to attend this webinar?',
    },
    professionOptions: [
      'Student',
      'Homemaker',
      'Job Seeker',
      'Working Professional',
      'Freelancer',
      'Entrepreneur',
      'Career Restarter',
      'Other',
    ],
    goalOptions: [
      'Career Restart',
      'Job Preparation',
      'Freelancing',
      'Work From Home',
      'Digital Skills',
      'Entrepreneurship',
      'Personal Growth',
      'Confidence Building',
      'Skill Development',
      'Other',
    ],
    consent: 'I agree to receive webinar confirmation, reminders and related updates through WhatsApp, phone or email.',
    privacyLabel: 'Privacy Policy',
    termsLabel: 'Terms & Conditions',
    submitCta: 'Reserve My Free Seat',
    submittingLabel: 'Reserving your seat…',
    errors: {
      fullName: 'Please enter your full name.',
      mobile: 'Please enter a valid 10-digit mobile number.',
      whatsapp: 'Please enter a valid 10-digit WhatsApp number.',
      email: 'Please enter a valid email address.',
      city: 'Please enter your city.',
      profession: 'Please select your profession.',
      consent: 'Please agree to receive updates to continue.',
    },
  },
  faq: {
    heading: 'Frequently Asked Questions',
    items: [
      { question: 'Is this webinar only for working women?', answer: 'No. The webinar is for students, homemakers, career restarters, job seekers, beginners and women exploring new opportunities.' },
      { question: 'Do I need prior experience?', answer: 'No. The webinar is beginner-friendly.' },
      { question: 'Do I need technical knowledge?', answer: 'No advanced technical knowledge is required.' },
      { question: 'Will I learn a specific skill during the webinar?', answer: 'The webinar focuses on helping you identify useful skills, choose a direction and understand how skills can connect with practical opportunities.' },
      { question: 'Can homemakers attend?', answer: 'Absolutely. Homemakers who want to learn, explore work, develop skills or create new opportunities are welcome.' },
      { question: 'Can I attend if I have a career gap?', answer: 'Yes. Career restarters are one of the intended audiences for this webinar.' },
      { question: 'Will I get a recording?', answer: 'Only if a recording is provided for this specific session — this will be confirmed before the webinar.' },
      { question: 'Will I receive a certificate?', answer: 'Only if a certificate is provided for this specific session — this will be confirmed before the webinar.' },
      { question: 'How will I receive webinar details?', answer: 'Registration details and reminders can be sent through WhatsApp and email.' },
    ],
  },
  finalCta: {
    heading: "You Don't Need to Have Everything Figured Out. You Just Need to Take the First Step.",
    supporting:
      'Join this practical, beginner-friendly webinar and discover how skills, confidence and direction can help you create new possibilities for your future.',
    cta: 'Reserve My Free Seat',
  },
  footer: {
    companyPlaceholder: '[Company Name]',
    aboutPlaceholder: '[About the organizer — add real company information before launch]',
    contactPlaceholder: '[Support email / phone / WhatsApp]',
    privacyLabel: 'Privacy Policy',
    termsLabel: 'Terms & Conditions',
    disclaimerLabel: 'Disclaimer',
    copyright: `© ${new Date().getFullYear()} [Company Name]. All rights reserved.`,
  },
  thankYou: {
    heading: 'Congratulations! Your Registration Is Confirmed.',
    labels: {
      name: 'Name',
      registrationId: 'Registration ID',
      date: 'Date',
      time: 'Time',
      duration: 'Duration',
      mode: 'Mode',
    },
    calendarCta: 'Add to Google Calendar',
    calendarUnavailable: 'Calendar link will be available once the webinar date is confirmed.',
    whatsappCta: 'Join WhatsApp Community',
    instructions: [
      'Join the webinar 10 minutes before it starts.',
      'Keep a notebook and pen ready.',
    ],
    supportNote: 'Questions? Reach out using the contact details in the footer.',
  },
};
