import type { SiteContent } from './types';

export const hi: SiteContent = {
  meta: {
    title: 'Women Skill Development Webinar',
    description: 'Skills सीखिए। Confidence बढ़ाइए। अपने लिए नए Opportunities बनाइए।',
  },
  announcementBar: {
    message: 'Limited Seats Available | Free Live Webinar | Registration जल्द बंद हो रही है',
    visible: true,
  },
  eventInfo: {
    heading: 'Event Details',
    items: [
      { label: 'तारीख', value: '[Webinar Date]' },
      { label: 'समय', value: '[Webinar Time]' },
      { label: 'अवधि', value: '90–120 मिनट' },
      { label: 'माध्यम', value: 'Live Online Webinar' },
      { label: 'भाषा', value: 'Hindi + English' },
      { label: 'Level', value: 'Beginner Friendly' },
    ],
  },
  whyImportant: {
    heading: 'यह Webinar आपके लिए क्यों Important है?',
    paragraphs: [
      'यह webinar हर महिला को एक ही career path follow करने के लिए कहने के बारे में नहीं है। इसका उद्देश्य आपको यह समझने में मदद करना है कि useful skills को कैसे identify करें, अपने लिए सही direction कैसे चुनें, confidence कैसे build करें और learning को practical opportunities में कैसे बदलें।',
      'चाहे आपका goal नौकरी हो, freelancing हो, entrepreneurship हो, career restart हो या personal growth—पहला कदम यह समझना है कि कौन-सी skills real world में आपके लिए value create कर सकती हैं।',
    ],
  },
  problems: {
    heading: 'क्या आपको भी ऐसा लगता है?',
    items: [
      'आप अपना career restart करना चाहती हैं, लेकिन समझ नहीं आता कि शुरुआत कहाँ से करें।',
      'आपके career में gap है और आपको लगता है कि शायद आपकी skills अब relevant नहीं हैं।',
      'आप work from home करना चाहती हैं या अपनी income का एक additional source बनाना चाहती हैं।',
      'आप technology, communication और professional work में अपना confidence बढ़ाना चाहती हैं।',
      'आपको लगता है कि आपके अंदर potential है, लेकिन आपको सही direction, practical skills और एक clear starting point की जरूरत है।',
      'आप कुछ valuable सीखना चाहती हैं, लेकिन इतने सारे courses और career options देखकर confused हो जाती हैं।',
    ],
    closing: 'अगर इनमें से कोई एक situation भी आपकी life से जुड़ी हुई लगती है, तो यह webinar आपके लिए है।',
  },
  lifeTransitions: {
    heading: 'आपकी Life बदल सकती है। आपकी Skills भी आपके साथ Grow कर सकती हैं।',
    paragraphs: [
      'समय के साथ आपकी responsibilities बदल सकती हैं। आज आप पढ़ाई कर रही हों, कल family manage कर रही हों, career break ले रही हों, दोबारा work पर लौट रही हों या अपने लिए कुछ शुरू करने का decision ले रही हों।',
      'परिस्थितियाँ बदल सकती हैं, लेकिन सीखने की आपकी ability हमेशा आगे बढ़ सकती है।',
      'Skills आपको अपने decisions लेने के लिए ज्यादा choices और ज्यादा confidence दे सकती हैं।',
    ],
  },
  learn: {
    heading: 'इस Webinar में आप क्या सीखेंगी?',
    items: [
      { title: 'Identify Valuable Skills', description: 'आज के job market के लिए practical और valuable skills को कैसे identify करें।' },
      { title: 'Digital Skills', description: 'Digital skills career और work-from-home opportunities कैसे create कर सकती हैं।' },
      { title: 'Communication & Confidence', description: 'Professional communication और confidence कैसे build करें।' },
      { title: 'Turn Skills Into Opportunities', description: 'सीखी हुई skill को practical opportunity में कैसे बदलें।' },
    ],
  },
  framework: {
    heading: 'अपने लिए सही Skill कैसे चुनें?',
    steps: [
      { title: 'Know Yourself', description: 'अपनी interests, strengths, experience और goals को समझें।' },
      { title: 'Understand Opportunities', description: 'ऐसी skills identify करें जो real world में value create कर सकती हैं।' },
      { title: 'Choose One Direction', description: 'एक साथ सब कुछ सीखने की कोशिश न करें। एक practical direction से शुरुआत करें।' },
      { title: 'Learn & Practice', description: 'Skill सीखें और उसे practical work के through apply करना शुरू करें।' },
      { title: 'Create an Opportunity', description: 'देखें कि आपकी skill को job, freelancing, work-from-home, business या personal growth से कैसे connect किया जा सकता है।' },
    ],
  },
  examples: {
    heading: 'देखिए एक Skill कैसे Opportunity बन सकती है',
    items: [
      { title: 'Digital Skills', chain: 'Skill → Digital Work → Career/Work Opportunity' },
      { title: 'Communication', chain: 'Skill → Better Professional Communication → Workplace Confidence' },
      { title: 'Freelancing Skill', chain: 'Skill → Portfolio/Practice → Freelancing Opportunity' },
      { title: 'Business Skill', chain: 'Skill → Practical Application → Entrepreneurship Opportunity' },
    ],
    disclaimer: 'ये उदाहरण learning और opportunity के बीच एक possible connection दिखाते हैं — guaranteed income या employment का वादा नहीं।',
  },
  video: {
    heading: 'यह Webinar आपके लिए क्यों जरूरी है?',
    placeholderNote: 'Intro video (60–90 सेकंड) — recording होने के बाद यहाँ add करें।',
  },
  audience: {
    heading: 'यह Webinar किन महिलाओं के लिए है?',
    items: [
      { title: 'College Students', description: 'ऐसी students जो शुरुआत से useful skills develop करना चाहती हैं।' },
      { title: 'Homemakers', description: 'ऐसी homemakers जो learning, work या independent opportunities explore करना चाहती हैं।' },
      { title: 'Career Restarters', description: 'ऐसी महिलाएँ जो career break के बाद professional life में वापस आना चाहती हैं।' },
      { title: 'Job Seekers', description: 'ऐसी महिलाएँ जो अपनी skills improve करके नई opportunities के लिए prepare करना चाहती हैं।' },
      { title: 'Work-from-Home Seekers', description: 'ऐसी महिलाएँ जो work-from-home possibilities explore करना चाहती हैं।' },
      { title: 'Beginners', description: 'ऐसी महिलाएँ जो सीखना चाहती हैं लेकिन शुरुआत कहाँ से करें, यह समझ नहीं पा रही हैं।' },
    ],
    cta: 'हाँ, यह Webinar मेरे लिए है',
  },
  transformation: {
    heading: 'Confusion से Clarity तक',
    beforeLabel: 'Before',
    afterLabel: 'After',
    before: [
      'कौन-सी skill सीखें, यह समझ नहीं आता',
      'Career options को लेकर confusion',
      'Confidence की कमी',
      'Career gap को लेकर चिंता',
      'शुरुआत कैसे करें, यह clear नहीं',
      'बहुत सारे courses देखकर confusion',
      'Skill को opportunity में कैसे बदलें, यह नहीं पता',
    ],
    after: [
      'Useful skills की बेहतर understanding',
      'ज्यादा clear direction',
      'बेहतर confidence',
      'Practical learning approach',
      'Opportunities की बेहतर understanding',
      'Realistic learning path',
      'अगला step क्या होना चाहिए, इसकी clarity',
    ],
  },
  trainer: {
    heading: 'अपने Trainer से मिलिए',
    placeholderNote: 'Trainer का नाम, designation, company, experience और social links यहाँ आएंगे — केवल real और verified जानकारी। Placeholder credentials के साथ यह section publish न करें।',
  },
  testimonials: {
    heading: 'Participants का अनुभव',
    emptyState: 'पहले cohort के बाद real participants के testimonials यहाँ दिखाई देंगे। हम fabricated reviews publish नहीं करते।',
  },
  bonuses: {
    heading: 'आज Register करें और ये Resources पाएं',
    items: [
      'Women Skill Development Checklist',
      'Skill Selection Worksheet',
      'Career Direction Worksheet',
      'Digital Skills Starter Guide',
      'Learning Roadmap',
    ],
    note: 'Webinar recording और certificate केवल तभी list किए जाते हैं जब वे इस session के लिए actually provide किए जा रहे हों।',
  },
  whatsappCommunity: {
    heading: 'हमारी WhatsApp Community से जुड़ें',
    supporting: 'Webinar updates, reminders पाएं और दूसरे participants से जुड़ें — बिल्कुल free, सबके लिए open।',
    cta: 'WhatsApp Community Join करें',
  },
  registration: {
    heading: 'क्या आप अपना पहला Step लेने के लिए Ready हैं?',
    supporting:
      'इस free webinar में जुड़ें और ऐसे practical ideas सीखें जिन्हें आप अपने career, work, communication, confidence और personal growth में apply कर सकती हैं।',
    labels: {
      fullName: 'पूरा नाम',
      mobile: 'मोबाइल नंबर',
      whatsapp: 'WhatsApp नंबर',
      email: 'ईमेल',
      city: 'शहर',
      profession: 'आपका Profession',
      goal: 'आप यह Webinar क्यों Attend करना चाहती हैं?',
    },
    professionOptions: [
      'Student',
      'Homemaker',
      'Job Seeker',
      'Working Professional',
      'Freelancer',
      'Entrepreneur',
      'Career Restarter',
      'अन्य',
    ],
    goalOptions: [
      'Career Restart',
      'Job Preparation',
      'Freelancing',
      'Work From Home',
      'Digital Skills',
      'Entrepreneurship',
      'Personal Growth',
      'Confidence Building',
      'Skill Development',
      'अन्य',
    ],
    consent: 'मैं WhatsApp, phone या email के माध्यम से webinar confirmation, reminders और संबंधित updates प्राप्त करने के लिए सहमत हूँ।',
    privacyLabel: 'Privacy Policy',
    termsLabel: 'Terms & Conditions',
    submitCta: 'अपनी Free Seat Reserve करें',
    submittingLabel: 'आपकी Seat Reserve हो रही है…',
    errors: {
      fullName: 'कृपया अपना पूरा नाम दर्ज करें।',
      mobile: 'कृपया एक valid 10-digit मोबाइल नंबर दर्ज करें।',
      whatsapp: 'कृपया एक valid 10-digit WhatsApp नंबर दर्ज करें।',
      email: 'कृपया एक valid ईमेल दर्ज करें।',
      city: 'कृपया अपना शहर दर्ज करें।',
      profession: 'कृपया अपना profession चुनें।',
      consent: 'आगे बढ़ने के लिए कृपया updates प्राप्त करने के लिए सहमत हों।',
    },
  },
  faq: {
    heading: 'अक्सर पूछे जाने वाले सवाल',
    items: [
      { question: 'क्या यह webinar सिर्फ working women के लिए है?', answer: 'नहीं। यह webinar students, homemakers, career restarters, job seekers, beginners और नई opportunities explore करने वाली महिलाओं के लिए है।' },
      { question: 'क्या मुझे prior experience चाहिए?', answer: 'नहीं। यह webinar beginners के लिए है।' },
      { question: 'क्या मुझे technical knowledge चाहिए?', answer: 'किसी advanced technical knowledge की जरूरत नहीं है।' },
      { question: 'क्या मैं webinar में कोई specific skill सीखूंगी?', answer: 'Webinar का focus useful skills identify करने, सही direction choose करने और skills को practical opportunities से connect करने की understanding देने पर है।' },
      { question: 'क्या homemakers attend कर सकती हैं?', answer: 'बिल्कुल। ऐसी homemakers जो सीखना, work explore करना, skills develop करना या नई opportunities create करना चाहती हैं, वे इस webinar में join कर सकती हैं।' },
      { question: 'अगर मेरे career में gap है तो क्या मैं attend कर सकती हूँ?', answer: 'हाँ। Career gap के बाद professional life में वापस आने वाली महिलाएँ इस webinar के लिए intended audience में शामिल हैं।' },
      { question: 'क्या मुझे recording मिलेगी?', answer: 'सिर्फ तभी जब इस specific session के लिए recording provide की जा रही हो — यह webinar से पहले confirm किया जाएगा।' },
      { question: 'क्या मुझे certificate मिलेगा?', answer: 'सिर्फ तभी जब इस specific session के लिए certificate provide किया जा रहा हो — यह webinar से पहले confirm किया जाएगा।' },
      { question: 'मुझे webinar details कैसे मिलेंगी?', answer: 'Registration details और reminders WhatsApp और email के माध्यम से भेजे जा सकते हैं।' },
    ],
  },
  finalCta: {
    heading: 'आपको आज सब कुछ पता होना जरूरी नहीं है। आपको बस पहला कदम उठाना है।',
    supporting:
      'इस practical और beginner-friendly webinar में जुड़ें और समझें कि skills, confidence और सही direction आपके future के लिए नई possibilities कैसे create कर सकते हैं।',
    cta: 'अपनी Free Seat Reserve करें',
  },
  footer: {
    companyPlaceholder: '[Company Name]',
    aboutPlaceholder: '[Organizer के बारे में — launch से पहले real company information जोड़ें]',
    contactPlaceholder: '[Support email / phone / WhatsApp]',
    privacyLabel: 'Privacy Policy',
    termsLabel: 'Terms & Conditions',
    disclaimerLabel: 'Disclaimer',
    copyright: `© ${new Date().getFullYear()} [Company Name]. सर्वाधिकार सुरक्षित।`,
  },
  thankYou: {
    heading: 'Congratulations! आपका Registration Confirm हो गया है।',
    labels: {
      name: 'नाम',
      registrationId: 'Registration ID',
      date: 'तारीख',
      time: 'समय',
      duration: 'अवधि',
      mode: 'माध्यम',
    },
    calendarCta: 'Google Calendar में Add करें',
    calendarUnavailable: 'Webinar की तारीख confirm होने के बाद calendar link उपलब्ध होगा।',
    whatsappCta: 'WhatsApp Community Join करें',
    instructions: [
      'Webinar शुरू होने से 10 मिनट पहले join करें।',
      'Notebook और pen साथ रखें।',
    ],
    supportNote: 'कोई सवाल है? Footer में दी गई contact details का उपयोग करें।',
  },
};
